# Site wide configuration

title: Exercices de mathématiques - Ginette MPSI
locale: fr
logo: # filename of a logo image that has been placed into your images directory
description: > # this means to ignore newlines until "baseurl:"
  par Dan Meller 

# Enter the following platform usernames if you would like for them to appear on your site.
author:
  name: Dan Meller
  bio: "X2019"
  github: danmlr
  researchgate: Dan-Meller

google_analytics: G-ZEYG2GCPFV

