# Site wide configuration

title: Exercices de mathématiques - Ginette MPSI
locale: fr
logo: # filename of a logo image that has been placed into your images directory
description: > # this means to ignore newlines until "baseurl:"
  Exercices de mathématiques - MPSI - Ginette : Ces exercices ont été choisis ou conçus pour découvrir le programme sous l’angle de problèmes
  assez variés, voire parfois exotiques. Les techniques utilisées dans les résolutions sont cependant relativement
  universelles et permettent d’appliquer des notions de cours importantes, souvent à la croisée
  de plusieurs chapitres. Certains exercices permettent également d’aborder des éléments importants de
  culture mathématique avec les outils du programme.
  Les exercices marqués par un delta sont considérés comme classiques. Des éléments de correction sontsystématiquement donnés quand la technique de résolution ne découle pas simplement de l’énoncé de
  la question.

# Enter the following platform usernames if you would like for them to appear on your site.
owner:
  name: Dan Meller
  bio: "X2019"
  # Do not include the @ symbol in your Twitter username
  linkedin: #username
  github: danmlr
  orcid: # ID Number (ex. 0000-0000-0000-0000)
  researchgate: Dan-Meller
